"""Batch operations — generate synthetic data, run pipeline, get report."""

from fastapi import APIRouter
from app.db.database import get_supabase
from app.synthetic.generator import generator
from app.cache.feature_store import feature_store
import structlog

logger = structlog.get_logger()
router = APIRouter()


@router.post("/batch/generate")
async def generate_synthetic_data(count: int = 150, duration_days: int = 7):
    """Generate synthetic failed payments and store in Supabase."""
    db = get_supabase()

    # Generate customers
    customers = generator.generate_customers(n=50)
    for c in customers:
        try:
            db.table("customers").upsert(c, on_conflict="customer_id").execute()
        except Exception:
            pass  # Skip duplicates

    # Generate failures
    payments, labels = generator.generate_failures(
        n=count, customers=customers, duration_days=duration_days
    )

    # Store in Supabase
    stored = 0
    for payment, label in zip(payments, labels):
        record = {
            "payment_id": payment.payment_id,
            "order_id": payment.order_id,
            "amount": payment.amount,
            "currency": payment.currency,
            "method": payment.method.value,
            "bank": payment.bank,
            "wallet": payment.wallet,
            "vpa": payment.vpa,
            "error_code": payment.error_code,
            "error_source": payment.error_source.value,
            "error_step": payment.error_step,
            "error_reason": payment.error_reason,
            "error_description": payment.error_description,
            "customer_contact": payment.customer_contact,
            "customer_email": payment.customer_email,
            "is_recurring": payment.is_recurring,
            "created_at": payment.created_at.isoformat(),
        }
        try:
            db.table("payments").insert(record).execute()
            stored += 1

            # Update feature store with synthetic bank health data
            await feature_store.update_bank_event(payment.bank, success=False)
            await feature_store.update_method_event(payment.method.value, success=False)
        except Exception as e:
            logger.warning("batch.insert_failed", payment_id=payment.payment_id, error=str(e))

    # Store labels mapping (for training)
    for payment, label in zip(payments, labels):
        try:
            db.table("recovery_sessions").insert({
                "payment_id": payment.payment_id,
                "status": "OPEN",
                "root_cause": label,
            }).execute()
        except Exception:
            pass

    logger.info("batch.generated", total=count, stored=stored)

    return {
        "status": "success",
        "generated": count,
        "stored": stored,
        "customers": len(customers),
        "distribution": {rc: labels.count(rc) for rc in set(labels)},
    }


@router.post("/batch/run")
async def run_batch_pipeline():
    """Run the real recovery pipeline on every OPEN session.

    This delegates to `worker.process_failed_payment`, the same function the webhook
    queues on live traffic. It used to be a second, parallel implementation of the
    pipeline, and the copy had drifted into something much worse than duplication: it
    skipped the compliance check and the executor entirely, then *invented* the outcome
    with `random.random()` against a table of recovery rates keyed on the classifier's
    own prediction. It wrote that coin flip to the database as `SYSTEM_RECOVERED` and
    fed it to `bandit.update()` as a reward.

    Three separate untruths came out of that. The dashboard's recovery rate was a
    property of the random seed. The audit trail asserted causation for events that
    never happened. And the bandit was learning from a signal generated by the
    classifier it was supposed to be independent of, so its arms converged on whatever
    the model was confident about — which looks like learning and is not.

    Outcomes now arrive the only way they honestly can: from Razorpay, through the
    `payment.captured` and `payment_link.paid` webhooks, which is where attribution and
    the bandit update live. A session left `OPEN` after this endpoint runs has not
    failed; it is a payment with an action taken and no answer yet.
    """
    from app.worker import process_failed_payment

    db = get_supabase()

    sessions = db.table("recovery_sessions").select("payment_id").eq("status", "OPEN").execute()
    if not sessions.data:
        return {"status": "no_data", "message": "No open recovery sessions found."}

    results = {"total": len(sessions.data), "processed": 0, "errored": 0}
    for session in sessions.data:
        try:
            # `ctx` is ARQ's job context, which this pipeline does not read.
            await process_failed_payment({}, session["payment_id"])
            results["processed"] += 1
        except Exception as exc:
            logger.error(
                "batch.payment_error", payment_id=session["payment_id"], error=str(exc)
            )
            results["errored"] += 1

    statuses = db.table("recovery_sessions").select("status").execute()
    counts: dict[str, int] = {}
    for row in (statuses.data or []):
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    logger.info("batch.pipeline_complete", **results)
    return {
        "status": "complete",
        "results": results,
        "sessions_by_status": counts,
        "note": (
            "Recovery outcomes are not decided here. Sessions stay OPEN until Razorpay "
            "reports a capture or a paid link, which is what closes them and what the "
            "bandit learns from."
        ),
    }
