"""Batch operations — generate synthetic data, run pipeline, get report."""

from fastapi import APIRouter
from app.db.database import get_supabase, select_all
from app.synthetic.generator import generator
from app.cache.feature_store import feature_store
import structlog

logger = structlog.get_logger()
router = APIRouter()


@router.post("/batch/generate")
async def generate_synthetic_data(count: int = 150, duration_days: int = 7):
    """Generate synthetic failed payments and store in Supabase."""
    db = get_supabase()

    # Generate customers
    customers = generator.generate_customers(n=50)
    for c in customers:
        try:
            db.table("customers").upsert(c, on_conflict="customer_id").execute()
        except Exception:
            pass  # Skip duplicates

    # Generate failures
    payments, labels = generator.generate_failures(
        n=count, customers=customers, duration_days=duration_days
    )

    # Store in Supabase
    stored = 0
    for payment, label in zip(payments, labels):
        record = {
            "payment_id": payment.payment_id,
            "order_id": payment.order_id,
            "amount": payment.amount,
            "currency": payment.currency,
            "method": payment.method.value,
            "bank": payment.bank,
            "wallet": payment.wallet,
            "vpa": payment.vpa,
            "error_code": payment.error_code,
            "error_source": payment.error_source.value,
            "error_step": payment.error_step,
            "error_reason": payment.error_reason,
            "error_description": payment.error_description,
            "customer_contact": payment.customer_contact,
            "customer_email": payment.customer_email,
            "is_recurring": payment.is_recurring,
            "created_at": payment.created_at.isoformat(),
        }
        try:
            db.table("payments").insert(record).execute()
            stored += 1

            # Update feature store with synthetic bank health data
            await feature_store.update_bank_event(payment.bank, success=False)
            await feature_store.update_method_event(payment.method.value, success=False)
        except Exception as e:
            logger.warning("batch.insert_failed", payment_id=payment.payment_id, error=str(e))

    # Store labels mapping (for training)
    for payment, label in zip(payments, labels):
        try:
            db.table("recovery_sessions").insert({
                "payment_id": payment.payment_id,
                "status": "OPEN",
                "root_cause": label,
            }).execute()
        except Exception:
            pass

    logger.info("batch.generated", total=count, stored=stored)

    return {
        "status": "success",
        "generated": count,
        "stored": stored,
        "customers": len(customers),
        "distribution": {rc: labels.count(rc) for rc in set(labels)},
    }


@router.post("/batch/run")
async def run_batch_pipeline(limit: int = 0):
    """Run the real recovery pipeline on the open sessions, oldest first.

    This delegates to `worker.process_failed_payment`, the same function the webhook
    queues on live traffic. It used to be a second, parallel implementation of the
    pipeline, and the copy had drifted into something much worse than duplication: it
    skipped the compliance check and the executor entirely, then *invented* the outcome
    with `random.random()` against a table of recovery rates keyed on the classifier's
    own prediction. It wrote that coin flip to the database as `SYSTEM_RECOVERED` and
    fed it to `bandit.update()` as a reward.

    Three separate untruths came out of that. The dashboard's recovery rate was a
    property of the random seed. The audit trail asserted causation for events that
    never happened. And the bandit was learning from a signal generated by the
    classifier it was supposed to be independent of, so its arms converged on whatever
    the model was confident about — which looks like learning and is not.

    Outcomes now arrive the only way they honestly can: from Razorpay, through the
    `payment.captured` and `payment_link.paid` webhooks, which is where attribution and
    the bandit update live. A session left `OPEN` after this endpoint runs has not
    failed; it is a payment with an action taken and no answer yet.

    `limit` bounds how many sessions this call works; `0` means all of them. It exists
    because the pipeline is network-bound on a hosted database — a classifier call, a
    compliance read, a bandit read, an action and several audit inserts, each a round trip —
    and a measured run of 137 sessions took 435 seconds. That is the honest cost of doing
    the real work per payment rather than a coin flip, and it is also longer than anybody
    watching a demo will wait. The slice is the oldest sessions rather than an arbitrary
    page, and the response says how many were left, because a partial run reported as a
    finished one is the class of claim this file exists to stop making.
    """
    from app.worker import process_failed_payment

    # Oldest first, so a bounded run works the payments that have been waiting longest
    # instead of whichever UUIDs happen to sort low.
    open_sessions = select_all(
        "recovery_sessions", "payment_id", status="OPEN", order_by="created_at"
    )
    if not open_sessions:
        return {"status": "no_data", "message": "No open recovery sessions found."}

    queued = len(open_sessions)
    if limit > 0:
        open_sessions = open_sessions[:limit]

    results = {"total": len(open_sessions), "processed": 0, "errored": 0}
    for session in open_sessions:
        try:
            # `ctx` is ARQ's job context, which this pipeline does not read.
            await process_failed_payment({}, session["payment_id"])
            results["processed"] += 1
        except Exception as exc:
            logger.error(
                "batch.payment_error", payment_id=session["payment_id"], error=str(exc)
            )
            results["errored"] += 1

    # Paged, and the reason is on the response of the last run: this table has passed a
    # thousand rows, and the census an unbounded `select()` returned summed to exactly 1000 —
    # `{ESCALATED: 60, FAILED: 610, OPEN: 108, RECOVERED: 222}`. That is PostgREST's
    # `db-max-rows` reported as a population, with no error and no truncation flag, on the one
    # number a reviewer would read as the state of the whole batch.
    counts: dict[str, int] = {}
    for row in select_all("recovery_sessions", "status"):
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    logger.info("batch.pipeline_complete", **results)
    return {
        "status": "complete",
        "results": results,
        # What was open when the run started, and what this call chose not to touch. A run
        # over a slice has to say so; `processed: 15` on its own reads as a finished batch.
        "open_at_start": queued,
        "not_worked_this_run": queued - len(open_sessions),
        "sessions_by_status": counts,
        "note": (
            "Recovery outcomes are not decided here. Sessions stay OPEN until Razorpay "
            "reports a capture or a paid link, which is what closes them and what the "
            "bandit learns from."
        ),
    }
